name: cocoapods-publish

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Updating submodules
      run: git submodule update --init --recursive
    - name: Get the version from tag
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Publish to Cocoapods
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        MANTLE_VERSION: ${{ steps.get_version.outputs.VERSION }}
      run: |
        # Modify the podspec with the version & tag and run lint on it
        jq '. | .version |= "$MANTLE_VERSION" | .source.tag |= "$MANTLE_VERSION"' Mantle.podspec.json
        pod spec lint Mantle.podspec.json

        # For now, just cat the final podspec; we'll modify this to pod trunk publish later
        cat Mantle.podspec.json
        # Uncomment below to enable publishing to Cocoapods
        # pod trunk push Mantle.podspec --skip-import-validation --allow-warnings
